language: minimal

os:
  - linux
  - osx

before_script:
  - curl -sL https://deno.land/x/install/install.sh | sh
  - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

script: ./check.sh
